(function(){
'use strict';
function onReady(fn){if(document.readyState==='complete')fn();else window.addEventListener('load',fn,{once:true});}
const q=id=>document.getElementById(id);
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
onReady(function(){
try{
if(typeof S==='undefined'||typeof CLUBS==='undefined')return;
document.title='Fairway Golf Core — Gameplay Overhaul';
S.shotType=S.shotType||'normal';S._fgFlightAge=null;if(typeof DIFF==='object'&&DIFF)DIFF.disp=0;
const ui=document.createElement('div');ui.id='fgGameplayUI';ui.innerHTML=`
<section id="fgShotPanel" class="fg-glass"><div class="fg-eyebrow">SHOT PLAN</div><div class="fg-metrics"><span><b id="fgCarry">—</b><small>CARRY</small></span><span><b id="fgTotal">—</b><small>TOTAL</small></span><span><b id="fgElev">—</b><small>ELEVATION</small></span></div><div id="fgLieLine">Reading lie…</div><div id="fgClubWarning"></div></section>
<section id="fgShotTypes" class="fg-glass"><div class="fg-eyebrow">SHOT TYPE</div><div class="fg-type-row">${[['normal','Normal'],['punch','Punch'],['knockdown','Knockdown'],['draw','Draw'],['fade','Fade'],['chip','Chip'],['pitch','Pitch'],['flop','Flop'],['splash','Splash']].map(([v,l])=>`<button type="button" data-shot="${v}">${l}</button>`).join('')}</div></section>
<section id="fgSwingDetails" class="fg-glass"><div id="fgSwingGrade">PURE</div><div class="fg-swing-grid"><span>CLUBFACE<b id="fgFace">Square</b></span><span>PATH<b id="fgPath">Straight</b></span><span>TEMPO<b id="fgTempo">3.0 : 1</b></span><span>CONTACT<b id="fgContact">Center</b></span></div><div id="fgBallResult">Straight flight</div></section>
<section id="fgPuttHint" class="fg-glass"><div class="fg-eyebrow">PUTT READ</div><b id="fgPuttDistance">—</b><span id="fgPuttPace">Trust your pace</span></section>`;document.body.appendChild(ui);
const buttons=[...document.querySelectorAll('[data-shot]')];
function setShotType(type){S.shotType=type;buttons.forEach(b=>b.classList.toggle('active',b.dataset.shot===type));}
buttons.forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();setShotType(b.dataset.shot);}));setShotType(S.shotType);
const swingPad=q('swingpad');if(swingPad)swingPad.addEventListener('pointerdown',()=>{window.__fgSwingStart=performance.now();},true);
const originalComputeStrike=typeof computeStrike==='function'?computeStrike:null;
if(originalComputeStrike){computeStrike=function(powerPct){
const lie=String(typeof currentLie==='function'?currentLie():'fairway').toLowerCase();const putter=CLUBS[S.club]&&CLUBS[S.club].loft===0;const deterministic=putter||['tee','fairway','green','fringe','firstcut','first cut'].includes(lie);let st;
if(deterministic){const random=Math.random;Math.random=()=>0.5;try{st=originalComputeStrike(powerPct);}finally{Math.random=random;}}else st=originalComputeStrike(powerPct);
if(!st||st.putter)return st;
switch(S.shotType){case'punch':st.loft=Math.max(4,st.loft-10);st.v*=.96;st.bs*=.48;st.rollBias=(st.rollBias||1)*1.55;break;case'knockdown':st.loft=Math.max(6,st.loft-6);st.v*=.92;st.bs*=.72;st.windLift=(st.windLift||1)*.58;st.rollBias=(st.rollBias||1)*1.25;break;case'flop':st.loft=Math.min(68,st.loft+17);st.v*=.70;st.bs*=1.26;st.rollBias=(st.rollBias||1)*.45;break;case'chip':st.loft=Math.min(30,Math.max(11,st.loft-8));st.v*=.54;st.bs*=.54;st.rollBias=(st.rollBias||1)*1.70;break;case'pitch':st.loft=Math.min(58,st.loft+5);st.v*=.72;st.bs*=.90;st.rollBias=(st.rollBias||1)*.78;break;case'splash':st.loft=Math.min(72,st.loft+21);st.v*=.61;st.bs*=.58;st.rollBias=(st.rollBias||1)*.34;break;case'draw':st.ss=clamp((st.ss||0)-.26,-1.1,1.1);break;case'fade':st.ss=clamp((st.ss||0)+.26,-1.1,1.1);break;}return st;};}
function signed(v){if(Math.abs(v)<.15)return'Square';return`${Math.abs(v).toFixed(1)}° ${v>0?'open':'closed'}`;}
function pathLabel(v){if(Math.abs(v)<.25)return'Straight';return`${Math.abs(v).toFixed(1)}° ${v>0?'outside-in':'inside-out'}`;}
function contactLabel(v){if(v>.35)return'Low-face / thin';if(v<-.35)return'High-face / heavy';if(Math.abs(v)>.16)return v>0?'Slightly thin':'Slightly heavy';return'Center';}
function shotResult(face,path){const curve=face-path;const start=Math.abs(face)<1?'Starts online':face>0?'Starts right':'Starts left';const shape=Math.abs(curve)<1?'straight':curve>0?(Math.abs(curve)>5?'slice':'fade'):(Math.abs(curve)>5?'hook':'draw');return`${start} · ${shape}`;}
function showDetailedFeedback(face,path,tempo,vertical,quality){const box=q('fgSwingDetails');if(!box)return;const v=clamp(quality,0,1);q('fgSwingGrade').textContent=v>.90?'PURE':v>.76?'SOLID':v>.58?'MISHIT':'POOR';q('fgSwingGrade').dataset.grade=v>.90?'pure':v>.76?'solid':v>.58?'miss':'poor';q('fgFace').textContent=signed(face);q('fgPath').textContent=pathLabel(path);q('fgTempo').textContent=`${tempo.toFixed(1)} : 1`;q('fgContact').textContent=contactLabel(vertical);q('fgBallResult').textContent=shotResult(face,path);box.classList.add('show');clearTimeout(S._fgFeedbackTimer);S._fgFeedbackTimer=setTimeout(()=>box.classList.remove('show'),4200);}
if(typeof fireSwing==='function'){fireSwing=function(x,y,now){
if(!sw)return;const gear=typeof gearStats==='function'?gearStats():{forg:0};const downTime=Math.max(.045,(now-sw.tFore)/1000);const backStart=window.__fgSwingStart||sw.tFore-700;const backTime=Math.max(.18,(sw.tFore-backStart)/1000);const tempoRatio=backTime/downTime;const travel=Math.max(1,sw.yAtMax-y);const speedNorm=clamp((travel/downTime)/(innerHeight*1.02),0,1.12);const scale=Math.min(innerWidth,innerHeight)*.082;const backDev=clamp((sw.xAtMax-sw.x0)/scale,-1,1);const foreDev=clamp((x-sw.xAtMax)/scale,-1,1);const forgiveness=clamp(1-(gear.forg+(DIFF.forg||0))*.55,.48,1.24);const vertical=Number(S.oy||0);const strikeX=Number(S.ox||0);const faceDeg=(backDev*5.2+strikeX*3.6)*forgiveness;const pathDeg=(foreDev*7.8)*forgiveness;const faceToPath=faceDeg-pathDeg;const tempoQuality=clamp(1-Math.abs(tempoRatio-3)/2.15,.58,1);const contactQuality=clamp(1-Math.abs(vertical)*.22,.78,1);const pathQuality=clamp(1-Math.max(Math.abs(faceDeg),Math.abs(pathDeg))/12,.55,1);const overall=tempoQuality*contactQuality*pathQuality;const isPutt=CLUBS[S.club]&&CLUBS[S.club].loft===0;const basePower=clamp(S.power,1,100);const speedPower=isPutt?1:clamp(.82+speedNorm*.18,.84,1.02);const power=isPutt?basePower:clamp(basePower*tempoQuality*contactQuality*speedPower,3,100);const curve=isPutt?0:clamp((faceToPath/5.2)*1.12,-1.35,1.35);const startShift=(faceDeg*(isPutt?.42:.72))*Math.PI/180;const trailPoints=sw.pts;sw=null;if(typeof hideSwingFeedback==='function')hideSwingFeedback();showDetailedFeedback(faceDeg,pathDeg,tempoRatio,vertical,overall);shoot(power,curve,startShift);if(trailPoints&&typeof swipeFadeOut==='function')swipeFadeOut(trailPoints);};}
const originalLaunchBall=typeof launchBall==='function'?launchBall:null;if(originalLaunchBall){launchBall=function(){originalLaunchBall();if(S.state==='flying')S._fgFlightAge=0;};}
const originalUpdateCamera=typeof updateCamera==='function'?updateCamera:null;if(originalUpdateCamera){updateCamera=function(dt){if(S.state==='flying')S._fgFlightAge=(S._fgFlightAge||0)+dt;else if(S.state!=='swinging')S._fgFlightAge=null;originalUpdateCamera(dt);if(S.state!=='flying'||!camera||!camPos)return;const age=S._fgFlightAge||0,h=H();if(age<.28){const d=aimDir(),p=S.lastShot,gy=surfaceWorldY(h,p.x,p.z),address=new THREE.Vector3(p.x-d.x*(MOBILE?9.5:8.2),gy+(MOBILE?3.8:3.4),p.z-d.z*(MOBILE?9.5:8.2));camera.position.lerp(address,.42);camPos.copy(camera.position);camera.lookAt(S.pos.x,S.pos.y+.6,S.pos.z);return;}const gy=surfaceWorldY(h,S.pos.x,S.pos.z),altitude=S.pos.y-gy;if(S.vel.y<-1.2&&altitude<15){const hv=new THREE.Vector3(S.vel.x,0,S.vel.z),d=hv.lengthSq()>.3?hv.normalize():aimDir(),landing=new THREE.Vector3(S.pos.x-d.x*10,S.pos.y+3.2,S.pos.z-d.z*10);camera.position.lerp(landing,Math.min(1,dt*3.6));camPos.copy(camera.position);camera.lookAt(S.pos.x,Math.max(gy,S.pos.y)+.35,S.pos.z);}};}
function setMaterialColor(obj,hex,opacity){if(!obj)return;const apply=m=>{if(!m)return;if(m.color&&m.color.setHex)m.color.setHex(hex);if(opacity!=null){m.transparent=true;m.opacity=opacity;}};if(obj.material)(Array.isArray(obj.material)?obj.material:[obj.material]).forEach(apply);if(obj.traverse)obj.traverse(n=>{if(n!==obj&&n.material)(Array.isArray(n.material)?n.material:[n.material]).forEach(apply);});}
function lieInfo(){const lie=String(typeof currentLie==='function'?currentLie():'fairway').toLowerCase(),club=CLUBS[S.club];let mult=1;try{mult=typeof lieMult==='function'?lieMult(lie==='tee'?'fairway':lie,club):1;}catch(e){}const pct=Math.max(0,Math.round((1-mult)*100));let warning='';if((lie==='rough'||lie==='deeprough'||lie==='deep rough')&&club&&/driver|wood/i.test(club.n))warning='Long club is unreliable from this lie';if((lie==='sand'||lie==='bunker')&&club&&club.loft<40)warning='Use more loft to escape the bunker';if(S.shotType==='splash'&&!/sand|bunker/.test(lie))warning='Splash is designed for sand';if(S.shotType==='flop'&&club&&club.loft<40)warning='Flop works best with a wedge';return{lie,mult,pct,warning};}
function updatePanels(){if(typeof golfMode==='function'&&!golfMode())return;const info=lieInfo(),club=CLUBS[S.club],gear=typeof gearStats==='function'?gearStats():{dist:0};let raw=120;try{raw=(CARRY_Y&&CARRY_Y[club.n])||Math.round((club.v||45)*2.4);}catch(e){}const aimPct=(S.aimPct==null?100:S.aimPct)/100;let typeCarry=1,roll=.08;if(S.shotType==='punch'){typeCarry=.91;roll=.24;}else if(S.shotType==='knockdown'){typeCarry=.88;roll=.16;}else if(S.shotType==='flop'){typeCarry=.62;roll=.02;}else if(S.shotType==='chip'){typeCarry=.42;roll=.45;}else if(S.shotType==='pitch'){typeCarry=.67;roll=.09;}else if(S.shotType==='splash'){typeCarry=.48;roll=.015;}const carry=Math.max(1,Math.round(raw*(1+(gear.dist||0))*aimPct*info.mult*typeCarry)),total=Math.max(carry,Math.round(carry*(1+roll)));let elevation=0;try{const h=H(),py=surfaceWorldY(h,h.pin.x,h.pin.z),by=surfaceWorldY(h,S.pos.x,S.pos.z);elevation=Math.round((py-by)*YDS*3);}catch(e){}q('fgCarry').textContent=carry+'y';q('fgTotal').textContent=total+'y';q('fgElev').textContent=(elevation>0?'+':'')+elevation+'ft';q('fgLieLine').innerHTML=`<b>${esc(info.lie.replace(/\b\w/g,c=>c.toUpperCase()))}</b> · ${info.pct?`${info.pct}% expected distance loss`:'clean contact expected'}`;q('fgClubWarning').textContent=info.warning;const putting=club&&club.loft===0&&['green','fringe'].includes(info.lie);document.body.classList.toggle('fg-putting',putting);q('fgPuttHint').style.display=putting?'block':'none';q('fgShotTypes').style.display=putting?'none':'block';if(putting){const feet=Math.max(1,Math.round(distToPin()*YDS*3));q('fgPuttDistance').textContent=feet+' ft';q('fgPuttPace').textContent=(feet<6?'Soft touch':feet<18?'Smooth pace':feet<35?'Firm pace':'Lag putt')+' · read the beads, not a percentage';const bt=q('breakTxt');if(bt)bt.innerHTML=bt.innerHTML.replace(/\s*·?\s*power\s*<b>\d+%<\/b>/i,'');}const aiming=S.state==='aiming'||S.state==='charging';q('fgShotPanel').style.opacity=aiming?'1':'.18';q('fgShotTypes').style.opacity=aiming?'1':'.18';}
const originalUpdateAimVisuals=typeof updateAimVisuals==='function'?updateAimVisuals:null;if(originalUpdateAimVisuals){updateAimVisuals=function(){originalUpdateAimVisuals();try{setMaterialColor(marker,0xffffff,1);setMaterialColor(landingArea,0xffffff,.18);setMaterialColor(rolloutMarker,0xffd34f,1);if(arcLine&&arcLine.material){arcLine.material.transparent=true;arcLine.material.opacity=.82;}}catch(e){}updatePanels();};}
setInterval(()=>{try{const lie=String(currentLie()).toLowerCase(),club=CLUBS[S.club];if(club&&club.loft===0)return;if((lie==='sand'||lie==='bunker')&&S.shotType==='normal'&&distToPin()*YDS<45)setShotType('splash');if(!/sand|bunker/.test(lie)&&S.shotType==='splash'&&S.state==='aiming')setShotType('normal');}catch(e){}},900);
console.info('Fairway Golf Core gameplay overhaul installed');
}catch(error){console.error('Gameplay overhaul failed',error);}
});
})();
