(()=>{
const S=window.SUNDAY,R=S?.R;if(!S||!R||S._realism5)return;S._realism5=true;
const FIRST=['Jalen','Malik','Cameron','Tyler','Jordan','Darius','Evan','Marcus','Andre','Devin','Mason','Trey','Cole','Isaiah','Noah','Elijah','Xavier','Jayden','Micah','Caleb','Bryce','Avery','Dante','Kendall'];
const LAST=['Mercer','Vance','Booker','Hale','Bennett','Pike','Wooten','Holloway','Rooks','Barrett','Lawson','Maddox','Sutton','Harris','McCall','Prescott','Foster','Carter','Ellis','Reed','Banks','Dawson','Hampton','Gaines'];
const groupPos={OL:['OT','OG','C'],SKILL:['WR','RB','TE'],DEF:['DL','LB','DB']};
const slot=[0,3800000,2100000,1450000,1150000,1020000,970000,940000];
R.needGroup=t=>{const avg=g=>{const f=g==='OL'?p=>['OT','OG','C','OL'].includes(p.pos):g==='SKILL'?p=>['RB','WR','TE'].includes(p.pos):p=>['DL','LB','DB'].includes(p.pos),a=t.roster.filter(p=>p.status==='ACT'&&f(p)).sort((x,y)=>y.overall-x.overall).slice(0,g==='OL'?5:g==='SKILL'?6:10);return a.length?a.reduce((n,p)=>n+p.overall,0)/a.length:50};return['OL','SKILL','DEF'].map(g=>[g,avg(g)]).sort((a,b)=>a[1]-b[1])[0][0]};
R.rookieName=(team,year,round,index)=>{const seed=Math.floor(R.hashRoll(`${team}|${year}|${round}|${index}|rookie`)*100000),f=FIRST[(seed+round*3)%FIRST.length],l=LAST[(seed*7+index+year)%LAST.length];return `${f} ${l}`};
R.makeRookie=(team,year,round,index,group)=>{const ps=groupPos[group]||groupPos.DEF,pos=ps[(year+round+index+team.length)%ps.length],name=R.rookieName(team,year,round,index),base={1:78,2:75,3:72,4:70,5:68,6:67,7:66}[round]||66,variance=Math.floor(R.hashRoll(`${team}|${name}|ovr`)*5)-2,o=S.clamp(base+variance,62,83),p=S.player(team,name,pos,round<=2?'Rotation':'Backup',o,`${team}-draft-${year}-${round}-${index}`);p.contract={expires:year+3,apy:slot[round],rookie:true,draftRound:round};p.practiceReps=round<=3?45:35;p.confidence=48;p.trust=45;p.developmentCeiling=S.clamp(o+7+Math.floor(R.hashRoll(`${name}|ceiling`)*10),72,96);return p};
R.draftRookie=priority=>{const t=R.team(),yr=S.state.season.year+1,capital=S.state.draftCapital[yr]||{1:1,2:1,3:1,4:1,5:1,6:1,7:1},classOut=[];for(let r=1;r<=7;r++){const count=Math.max(0,Number(capital[r]||0));for(let k=0;k<count;k++){const group=r===1?priority:R.needGroup(t),p=R.makeRookie(t.code,yr,r,k,group);t.roster.push(p);classOut.push(p);S.state.cap.spent2027+=Math.min(slot[r],Math.max(0,R.capRoom()));S.state.transactions.unshift({season:S.state.season.year,type:'Draft',player:p.name,text:`Round ${r} - ${p.pos}, ${p.overall} OVR.`})}}S.state.offseason.moves.push(`Drafted ${classOut.length} players across seven rounds`);S.addLog?.('offseason','Draft class complete',classOut.map(p=>`R${p.contract.draftRound} ${p.name} (${p.pos} ${p.overall})`).join(' · '),classOut.map(p=>p.id));return classOut[0]||null};
R.processLeagueOffseason=()=>{const yr=S.state.season.year+1;S.state.leagueOffseasons=S.state.leagueOffseasons||{};if(S.state.leagueOffseasons[yr])return;for(const t of Object.values(S.state.league)){if(t.code===S.state.coach.team)continue;for(const p of t.roster.filter(p=>p.status==='ACT')){const roll=R.hashRoll(`${yr}|${p.id}|dev`),delta=roll<.12?-2:roll<.32?-1:roll>.9?2:roll>.68?1:0;p.overall=S.clamp(p.overall+delta,60,97);p.attrs=S.attr(p.pos,p.overall)}for(let r=1;r<=7;r++){const group=R.needGroup(t),rook=R.makeRookie(t.code,yr,r,0,group);t.roster.push(rook)}let act=t.roster.filter(p=>p.status==='ACT');while(act.length>53){const protectedIds=new Set(act.filter(p=>['Featured','Starter'].includes(p.role)&&p.overall>=76).map(p=>p.id)),choices=act.filter(p=>!protectedIds.has(p.id)).sort((a,b)=>a.overall-b.overall),cut=choices[0]||act.sort((a,b)=>a.overall-b.overall)[0];cut.status='FA';act=t.roster.filter(p=>p.status==='ACT')}}S.state.leagueOffseasons[yr]=true;S.addLog?.('offseason','League roster turnover','All 31 CPU clubs completed modeled development, seven-round drafts and final 53-man cutdowns.')};
const priorCamp=R.campAndCuts;R.campAndCuts=()=>{R.processLeagueOffseason();return priorCamp()};
const priorAudit=S.realismAudit;S.realismAudit=()=>{const a=priorAudit(),next=S.state.season.year+1,userDraft=R.team().roster.filter(p=>p.contract?.rookie&&p.id.includes(`draft-${next}-`)).length;return{...a,version:'11.3-realism',userDraftedNextYear:userDraft,leagueOffseasonProcessed:!!S.state.leagueOffseasons?.[next],checks:{...a.checks,fullDraft:userDraft===0||userDraft>=6}}};
if(window.SUNDAY_QA)window.SUNDAY_QA.realismAudit=S.realismAudit;
S.render();
})();
