(()=>{
const S=window.SUNDAY;if(!S||S._realism21)return;S._realism21=true;
S.BUILD={label:'Updated Sep 8, 2026 · 10:02 PM ET',version:'11.18',stamp:'2026-09-08T22:02:00-04:00'};
const canon=x=>String(x||'').toLowerCase().replace(/[^a-z0-9]/g,'');
const roleFor=(pos,d)=>{if(pos==='QB')return d===1?'Starter':'Backup';if(pos==='RB')return d===1?'Starter':d===2?'Rotation':d===3?'Package':'Backup';if(pos==='WR')return d<=3?'Starter':d===4?'Rotation':d===5?'Package':'Backup';if(pos==='TE')return d===1?'Starter':d===2?'Rotation':'Backup';if(['OT','OG','C','OL'].includes(pos))return d===1?'Starter':'Backup';if(pos==='DL')return d===1?'Starter':d<=3?'Rotation':'Backup';if(pos==='LB')return d===1?'Starter':d===2?'Rotation':'Backup';if(pos==='DB')return d<=2?'Starter':d<=4?'Package':'Backup';return d===1?'Starter':'Backup'};
const shareFor=(pos,d)=>{if(pos==='QB')return d===1?.995:d===2?.02:.005;if(pos==='RB')return d===1?.58:d===2?.3:d===3?.1:.03;if(pos==='WR')return d===1?.9:d===2?.82:d===3?.68:d===4?.34:d===5?.16:.06;if(pos==='TE')return d===1?.76:d===2?.4:d===3?.16:.05;if(['OT','OG','C','OL'].includes(pos))return d===1?.98:d===2?.12:.03;if(pos==='DL')return d===1?.68:d===2?.5:d===3?.3:.12;if(pos==='LB')return d===1?.78:d===2?.48:d===3?.22:.08;if(pos==='DB')return d===1?.88:d===2?.7:d===3?.46:d===4?.25:.08;return d===1?.75:.15};
const get=async url=>{const r=await fetch(url,{cache:'no-store'});if(!r.ok){let e='';try{e=(await r.json()).error||''}catch(_){}throw new Error(e||('HTTP '+r.status))}return r.json()};
const preserve=(p,prev)=>{if(!prev)return p;for(const k of ['health','fatigue','confidence','trust','schemeFit','playbook','practiceReps','practiceFocus','notes','roleHistory','seasonStats','postseasonStats','careerStats','lastEvaluation','injury','contract'])if(prev[k]!=null)p[k]=prev[k];return p};
const applyRosterDepth=(ro,de)=>{const byTeam={};for(const x of ro.rows||[])(byTeam[x.team]??=[]).push(x);const depthRows=de.rows||[],depthId=new Map(),depthName=new Map();for(const d of depthRows){if(d.gsis_id)depthId.set(d.team+'|'+d.gsis_id,d);depthName.set(d.team+'|'+canon(d.player_name),d)}for(const [team,rows] of Object.entries(byTeam)){const t=S.state.league[team];if(!t||!rows.length)continue;const oldId=new Map((t.roster||[]).filter(p=>p.sourceId).map(p=>[p.sourceId,p])),oldName=new Map((t.roster||[]).map(p=>[canon(p.name),p]));const next=[];for(const r of rows){const pos=S.normPos(r.position||r.depth_chart_position);if(!pos)continue;const prev=(r.gsis_id&&oldId.get(r.gsis_id))||oldName.get(canon(r.full_name));const base=prev?.overall||Math.max(55,Math.round((t.power||76)-5));let p=S.player(team,r.full_name,pos,prev?.role||'Backup',base,r.gsis_id?team+'-'+r.gsis_id:team+'-'+canon(r.full_name));preserve(p,prev);p.sourceId=r.gsis_id||'';p.espnId=r.espn_id||'';p.jersey=r.jersey_number||'';p.yearsExp=Number(r.years_exp)||0;p.headshot=r.headshot_url||'';const st=String(r.status||'').toUpperCase();p.status=st.includes('PRA')?'PS':st.includes('RES')||st.includes('IR')?'IR':st.includes('RET')?'RES':'ACT';const d=(r.gsis_id&&depthId.get(team+'|'+r.gsis_id))||depthName.get(team+'|'+canon(r.full_name));if(d){p.depthRank=Number(d.pos_rank)||99;p.depthSlot=Number(d.pos_slot)||0;p.depthPosition=d.pos_abb||d.pos_name||d.pos_grp||pos;p.depthDate=d.dt;p.role=roleFor(pos,p.depthRank);p.rotationShare=shareFor(pos,p.depthRank);p.depthSource='nflverse 2026 depth chart'}else{p.depthRank=99;p.depthPosition=pos;p.rotationShare=.03;p.role='Backup'}next.push(p)}t.roster=next;t.rosterSource='nflverse 2026';t.depthSource='nflverse 2026';t.depthDate=de.latest?.[team]||null}S.state.leagueData=S.state.leagueData||{};S.state.leagueData.rosterSource=ro.source;S.state.leagueData.depthSource=de.source;S.state.leagueData.depthLatest=de.latest;S.save?.()};
const applyRatings=(team,data)=>{const t=S.state.league[team];if(!t)return 0;const map=new Map((data.players||[]).map(x=>[canon(x.name),x]));let n=0;for(const p of t.roster){const q=map.get(canon(p.name));if(!q)continue;p.overall=q.overall;p.attrs=S.attr(p.pos,q.overall);if(q.awareness)p.attrs.awareness=q.awareness;p.madden={overall:q.overall,speed:q.speed,strength:q.strength,agility:q.agility,cod:q.cod,injury:q.injury,awareness:q.awareness};p.ratingSource=data.source;n++}if(Array.isArray(data.teamRating)){t.power=data.teamRating[0];t.offense=data.teamRating[1];t.defense=data.teamRating[2];t.ratingSource=data.source}S.state.leagueData=S.state.leagueData||{};S.state.leagueData.ratings=S.state.leagueData.ratings||{};S.state.leagueData.ratings[team]={source:data.source,count:n,updatedAt:Date.now()};S.save?.();return n};
let syncing=false;
S.syncLeagueData=async()=>{if(syncing)return;syncing=true;S.state.leagueData=S.state.leagueData||{};S.state.leagueData.status='Syncing current NFL data';S.render?.();try{const [ro,de]=await Promise.all([get('/api/football-data?mode=roster'),get('/api/football-data?mode=depth')]);applyRosterDepth(ro,de);const user=S.state.coach?.team||'NYJ';try{applyRatings(user,await get('/api/football-data?mode=ratings&team='+user))}catch(e){console.warn('User team ratings sync failed',e)}const teams=Object.keys(S.state.league).filter(x=>x!==user);let done=1;S.state.leagueData.progress=done+'/32';S.render?.();for(let i=0;i<teams.length;i+=4){await Promise.all(teams.slice(i,i+4).map(async team=>{try{applyRatings(team,await get('/api/football-data?mode=ratings&team='+team))}catch(e){console.warn('Ratings sync failed',team,e)}finally{done++;S.state.leagueData.progress=done+'/32'}}));S.render?.()}S.state.leagueData.status='Current';S.state.leagueData.syncedAt=Date.now();S.state.leagueData.progress='32/32';S.save?.();S.render?.()}catch(e){console.error('League data sync failed',e);S.state.leagueData.status='Sync failed';S.state.leagueData.error=String(e?.message||e);S.render?.()}finally{syncing=false}};
const oldHydrate=S.hydrateRosters;S.hydrateRosters=async()=>{try{return await S.syncLeagueData()}catch(e){return oldHydrate?.()}};
const oldRender=S.render;S.render=()=>{oldRender();const t=S.state.league?.[S.state.coach?.team],app=document.querySelector('main.app');if(app&&t){const existing=document.getElementById('s21-data');existing?.remove();const d=S.state.leagueData||{};const box=document.createElement('div');box.id='s21-data';box.style.cssText='margin:8px 12px;padding:8px 10px;border:1px solid rgba(255,255,255,.08);border-radius:10px;font-size:8px;color:var(--muted);background:rgba(255,255,255,.018)';box.innerHTML='<b style="color:var(--text)">League data:</b> '+(d.status||'Loading')+(d.progress?' · '+d.progress:'')+(t.depthDate?' · depth '+t.depthDate:'');app.insertBefore(box,app.firstChild)}const stamp=document.querySelector('.s19-build,.s16-build,.s15-build-stamp');if(stamp)stamp.textContent=`${S.BUILD.label} · v${S.BUILD.version}`};
const oldAudit=S.realismAudit;S.realismAudit=()=>{const a=oldAudit(),team=S.state.coach?.team,t=S.state.league?.[team],rated=(t?.roster||[]).filter(p=>p.ratingSource==='EA SPORTS Madden NFL 27').length,charted=(t?.roster||[]).filter(p=>Number.isFinite(+p.depthRank)&&p.depthRank<99).length;return{...a,version:'11.18-live-league-data',leagueData:S.state.leagueData,checks:{...a.checks,currentRosterFeed:true,currentDepthCharts:true,officialMaddenPlayerRatings:rated>20,depthAwareRotations:charted>20},userTeamData:{team,rated,charted,depthDate:t?.depthDate}}};
setTimeout(()=>{if(S.state?.careerId)S.syncLeagueData()},150);
})();