(()=>{
const S=window.SUNDAY,R=S?.R;if(!S||!R||S._realism9)return;S._realism9=true;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const avg=a=>a.length?a.reduce((n,x)=>n+x,0)/a.length:0;
const topAvg=(a,n,fallback)=>{const x=a.filter(Number.isFinite).sort((p,q)=>q-p).slice(0,n);return x.length?avg(x):fallback};
R.ensureLeagueModel=()=>{const st=S.state;st.teamModels=st.teamModels||{};st.leagueGameHistory=st.leagueGameHistory||[];for(const code of Object.keys(st.league)){const meta=S.TEAMS[code],m=st.teamModels[code]||(st.teamModels[code]={code,baseYear:2026,base:{overall:meta?.[4]||st.league[code].power||76,offense:meta?.[5]||st.league[code].offense||76,defense:meta?.[6]||st.league[code].defense||76},formOff:0,formDef:0,history:[]});m.formOff=Number.isFinite(m.formOff)?m.formOff:0;m.formDef=Number.isFinite(m.formDef)?m.formDef:0;m.history=m.history||[]}return st.teamModels};
R.rosterComposite=t=>{const signed=t.roster.filter(p=>!['FA','PS'].includes(p.status)),off=signed.filter(p=>['QB','RB','WR','TE','OT','OG','C','OL'].includes(p.pos)),def=signed.filter(p=>['DL','LB','DB'].includes(p.pos)),fallback=t.power||76,q=topAvg(off.filter(p=>p.pos==='QB').map(p=>p.overall),1,fallback-1),ol=topAvg(off.filter(p=>['OT','OG','C','OL'].includes(p.pos)).map(p=>p.overall),5,fallback-2),rec=topAvg(off.filter(p=>['WR','TE'].includes(p.pos)).map(p=>p.overall),6,fallback-2),rb=topAvg(off.filter(p=>p.pos==='RB').map(p=>p.overall),3,fallback-3),odepth=topAvg(off.map(p=>p.overall),16,fallback-3),dl=topAvg(def.filter(p=>p.pos==='DL').map(p=>p.overall),5,fallback-2),lb=topAvg(def.filter(p=>p.pos==='LB').map(p=>p.overall),4,fallback-3),db=topAvg(def.filter(p=>p.pos==='DB').map(p=>p.overall),6,fallback-2),ddepth=topAvg(def.map(p=>p.overall),16,fallback-3),offense=q*.28+ol*.27+rec*.25+rb*.08+odepth*.12,defense=dl*.28+lb*.18+db*.34+ddepth*.20;return{offense,defense,overall:(offense+defense)/2,qb:q,ol,receivers:rec,front:dl*.6+lb*.4,coverage:db}};
R.syncTeamBaseline=code=>{R.ensureLeagueModel();const t=S.state.league[code],m=S.state.teamModels[code],source=S.state.rosterSource||'local';if(!m.rosterBaseline||(S.state.season.year===2026&&(t.teamStats?.games||0)===0&&m.baselineSource!==source)){m.rosterBaseline=R.rosterComposite(t);m.baselineSource=source;m.baselineCapturedSeason=S.state.season.year}return m};
R.injuryPenalty=t=>{let off=0,def=0,count=0;for(const p of t.roster){const unavailable=['OUT','IR'].includes(p.status)||p.injury&&['OUT','IR'].includes(p.injury.severity);if(!unavailable)continue;const role=['Featured','Starter'].includes(p.role)?1.35:p.role==='Rotation'?.7:.35,impact=clamp((p.overall-66)/13,.25,2.1)*role;if(['QB','RB','WR','TE','OT','OG','C','OL'].includes(p.pos))off+=impact;if(['DL','LB','DB'].includes(p.pos))def+=impact;count++}return{off:clamp(off,0,6.5),def:clamp(def,0,6.5),count}};
R.getTeamStrength=code=>{const t=S.state.league[code],m=R.syncTeamBaseline(code),cur=R.rosterComposite(t),baseR=m.rosterBaseline||cur,inj=R.injuryPenalty(t),rosterOff=cur.offense-baseR.offense,rosterDef=cur.defense-baseR.defense,user=code===S.state.coach.team,staffOff=user?((S.state.staff?.oc?.quality||80)-80)/10:0,staffDef=user?((S.state.staff?.dc?.quality||80)-80)/11:0,off=clamp(m.base.offense+rosterOff*1.18-inj.off+(m.formOff||0)*.85+staffOff,62,96),def=clamp(m.base.defense+rosterDef*1.18-inj.def+(m.formDef||0)*.85+staffDef,62,96),overall=clamp(off*.5+def*.5,62,96);return{code,overall:+overall.toFixed(1),offense:+off.toFixed(1),defense:+def.toFixed(1),baseOverall:m.base.overall,baseOffense:m.base.offense,baseDefense:m.base.defense,rosterOffDelta:+rosterOff.toFixed(1),rosterDefDelta:+rosterDef.toFixed(1),injuryOff:+inj.off.toFixed(1),injuryDef:+inj.def.toFixed(1),injuries:inj.count,formOff:+(m.formOff||0).toFixed(2),formDef:+(m.formDef||0).toFixed(2),qb:+cur.qb.toFixed(1)}};
R.recordLeagueGame=G=>{if(!G||S.state.season.phase==='POSTSEASON')return;R.ensureLeagueModel();for(const code of [G.away,G.home]){const opp=code===G.away?G.home:G.away,m=S.state.teamModels[code],s=R.getTeamStrength(code),os=R.getTeamStrength(opp),actual=G.score[code],allowed=G.score[opp],expPts=clamp(22+(s.offense-os.defense)*.72+(code===G.home?.7:0),13,34),expAllowed=clamp(22+(os.offense-s.defense)*.72+(opp===G.home?.7:0),13,34),offPerf=clamp((actual-expPts)/7,-2.5,2.5),defPerf=clamp((expAllowed-allowed)/7,-2.5,2.5);m.formOff=clamp((m.formOff||0)*.72+offPerf*.28,-2.5,2.5);m.formDef=clamp((m.formDef||0)*.72+defPerf*.28,-2.5,2.5);m.history.unshift({season:S.state.season.year,week:S.state.season.week,opp,points:actual,allowed,offPerf:+offPerf.toFixed(2),defPerf:+defPerf.toFixed(2),overall:s.overall});m.history=m.history.slice(0,40)}S.state.leagueGameHistory.unshift({season:S.state.season.year,week:S.state.season.week,away:G.away,home:G.home,score:{...G.score}});S.state.leagueGameHistory=S.state.leagueGameHistory.slice(0,700)};
const oldCommit=S.commitGame;S.commitGame=(G,user=false)=>{const out=oldCommit(G,user);R.recordLeagueGame(G);return out};
R.processCpuMedical=week=>{R.ensureLeagueModel();const key=`${S.state.season.year}-${week}`;if(S.state.cpuMedicalWeek===key)return;S.state.cpuMedicalWeek=key;for(const t of Object.values(S.state.league)){if(t.code===S.state.coach.team)continue;for(const p of t.roster){if(!p.injury?.cpu)continue;p.injury.weeksOut=Math.max(0,(p.injury.weeksOut||0)-1);if(p.injury.weeksOut<=0){p.injury=null;if(p.status==='OUT')p.status='ACT'}}const active=t.roster.filter(p=>p.status==='ACT'&&!['K','P','LS'].includes(p.pos));if(!active.length)continue;const r=R.hashRoll(`${key}|${t.code}|cpu-injury`);if(r>.22)continue;const weighted=[];for(const p of active){const n=['Featured','Starter'].includes(p.role)?3:p.role==='Rotation'?2:1;for(let i=0;i<n;i++)weighted.push(p)}const p=weighted[Math.floor(R.hashRoll(`${key}|${t.code}|pick`)*weighted.length)],sev=R.hashRoll(`${key}|${p.id}|severity`),weeks=sev<.58?1:sev<.86?2:sev<.96?3:4;p.injury={type:'football injury',weeksOut:weeks,severity:'OUT',cpu:true,season:S.state.season.year,week};p.status='OUT'}};
const oldRunDay=S.runDay;S.runDay=()=>{if(S.state.season.phase==='REGULAR'&&S.state.season.day===0)R.processCpuMedical(S.state.season.week);return oldRunDay()};
R.matchupContext=(away,home)=>{const a=R.getTeamStrength(away),h=R.getTeamStrength(home),spread=1.12,vr=(code,side)=>(R.hashRoll(`${S.state.season.year}|${S.state.season.week}|${away}|${home}|${code}|${side}|variance`)-.5)*2.2,scale=x=>80+(x-80)*spread;return{away,home,ratings:{[away]:{off:clamp(scale(a.offense)+vr(away,'o'),60,99),def:clamp(scale(a.defense)+vr(away,'d'),60,99),raw:a},[home]:{off:clamp(scale(h.offense)+1+vr(home,'o'),60,99),def:clamp(scale(h.defense)+1+vr(home,'d'),60,99),raw:h}},homeField:1,spread}};
const oldInit=S.initializeGame;S.initializeGame=(away,home)=>{const G=oldInit(away,home);G.ratingContext=R.matchupContext(away,home);return G};
const oldAdvance=S.advanceDrive;S.advanceDrive=G=>{if(!G?.ratingContext)return oldAdvance(G);const saved={};for(const code of [G.away,G.home]){const t=S.state.league[code],baseOff=S.TEAMS[code]?.[5]??t.offense,baseDef=S.TEAMS[code]?.[6]??t.defense,liveOffDelta=code===S.state.coach.team?t.offense-baseOff:0,liveDefDelta=code===S.state.coach.team?t.defense-baseDef:0;saved[code]={offense:t.offense,defense:t.defense,power:t.power};const r=G.ratingContext.ratings[code];t.offense=r.off+liveOffDelta;t.defense=r.def+liveDefDelta;t.power=(t.offense+t.defense)/2}const out=oldAdvance(G);for(const code of [G.away,G.home])Object.assign(S.state.league[code],saved[code]);return out};
R.expectedWins=()=>{const code=S.state.coach.team,sched=S.state.schedule.weeks||{},me=R.getTeamStrength(code);let exp=0,games=0;for(let w=1;w<=18;w++){for(const g of sched[w]||[]){if(g.away!==code&&g.home!==code)continue;const opp=g.away===code?g.home:g.away,os=R.getTeamStrength(opp),home=g.home===code?1.2:-1.2,diff=(me.overall-os.overall)+home,p=1/(1+Math.exp(-diff/7.6));exp+=p;games++}}return games?clamp(exp,2.5,14.5):8.5};
const oldNew=S.newSeason;S.newSeason=()=>{for(const m of Object.values(R.ensureLeagueModel())){m.formOff=(m.formOff||0)*.35;m.formDef=(m.formDef||0)*.35}for(const t of Object.values(S.state.league))for(const p of t.roster){if(p.injury?.cpu){p.injury=null;if(p.status==='OUT')p.status='ACT'}}const out=oldNew();S.state.cpuMedicalWeek=null;return out};
const oldRender=S.render;S.render=()=>{oldRender();if(typeof document==='undefined')return;const main=document.querySelector('main.app'),tab=S.state.ui.tab||'week';if(!main||!['week','league'].includes(tab))return;const us=R.getTeamStrength(S.state.coach.team),all=Object.keys(S.state.league).map(R.getTeamStrength).sort((a,b)=>b.overall-a.overall),rank=all.findIndex(x=>x.code===us.code)+1,top=all.slice(0,5),bot=all.slice(-5).reverse();const card=`<section class="section realism-card"><div class="section-head"><h2>Current team ability</h2><span>#${rank} of 32 · ${us.overall} OVR</span></div><div class="card grid3"><div class="metric"><b>${us.offense}</b><span>offense</span></div><div class="metric"><b>${us.defense}</b><span>defense</span></div><div class="metric"><b>${us.qb}</b><span>QB room</span></div></div><div class="notice">2026 ratings are the starting prior. Current strength moves from roster development/churn, injuries and recent underlying performance. Game-day variance is small; it cannot turn a weak roster into a contender by itself.</div></section>`;main.insertAdjacentHTML('afterbegin',card);if(tab==='league')main.insertAdjacentHTML('beforeend',`<section class="section realism-card"><div class="section-head"><h2>League strength model</h2><span>living ratings</span></div><div class="standings"><div class="card"><div class="eyebrow">Top 5 current</div>${top.map(x=>`<div class="standing-row"><span>${x.code}</span><b>${x.overall}</b></div>`).join('')}</div><div class="card"><div class="eyebrow">Bottom 5 current</div>${bot.map(x=>`<div class="standing-row"><span>${x.code}</span><b>${x.overall}</b></div>`).join('')}</div></div></section>`) };
R.ensureLeagueModel();
const oldAudit=S.realismAudit;S.realismAudit=()=>{const a=oldAudit(),mia=R.getTeamStrength('MIA');return{...a,version:'11.6-living-league',miamiStrength:mia,checks:{...a.checks,livingTeamStrength:true,scheduleExpectedWins:true,cpuInjuries:true,matchupStrengthAmplified:true}}};if(window.SUNDAY_QA){window.SUNDAY_QA.realismAudit=S.realismAudit;window.SUNDAY_QA.teamStrength=R.getTeamStrength;window.SUNDAY_QA.expectedWins=R.expectedWins}
S.render();
})();
