(()=>{
const S=window.SUNDAY,R=S?.R;if(!S||S._realism16)return;S._realism16=true;
S.BUILD={label:'Updated Sep 8, 2026 · 8:52 PM ET',version:'11.13',stamp:'2026-09-08T20:52:46-04:00'};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const style=document.createElement('style');style.textContent=`
.s16-today{margin:12px 0 14px;border:1px solid rgba(72,255,166,.2);border-radius:18px;background:linear-gradient(150deg,rgba(72,255,166,.065),rgba(255,255,255,.018));padding:15px;box-shadow:0 12px 40px rgba(0,0,0,.16)}.s16-top{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.s16-today h2{font-size:22px;line-height:1.05;margin:5px 0 4px}.s16-today p{margin:0;font-size:10px;line-height:1.45;color:var(--muted)}.s16-daybadge{flex:0 0 auto;border:1px solid rgba(72,255,166,.28);border-radius:999px;padding:6px 8px;color:var(--green);font-size:8px;font-weight:900;letter-spacing:.06em}.s16-focus{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:12px 0}.s16-focus div{border:1px solid var(--line);border-radius:11px;padding:9px;background:rgba(255,255,255,.018)}.s16-focus b{display:block;font-size:11px}.s16-focus span{display:block;font-size:8px;color:var(--muted);margin-top:3px;line-height:1.25}.s16-primary{width:100%;border:0;border-radius:13px;padding:14px;background:var(--green);color:#06100c;font-weight:950;font-size:11px;cursor:pointer}.s16-secondaryrow{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:8px}.s16-secondary{border:1px solid var(--line);border-radius:11px;padding:10px;background:rgba(255,255,255,.025);color:var(--text);font-weight:850;font-size:9px;cursor:pointer}.s16-hidden{display:none!important}.s16-note{margin-top:10px;border-top:1px solid var(--line);padding-top:9px;font-size:8px;color:var(--muted);line-height:1.35}.s16-offseason-watch{border-color:rgba(255,187,67,.24);background:linear-gradient(150deg,rgba(255,187,67,.055),rgba(255,255,255,.018))}.s16-offseason-watch .s16-daybadge{border-color:rgba(255,187,67,.3);color:#ffca69}.s16-offseason-watch .s16-primary{background:#e9d19c;color:#171109}.s16-build{position:fixed;right:9px;bottom:calc(76px + env(safe-area-inset-bottom));z-index:700;pointer-events:none;border:1px solid rgba(255,255,255,.09);border-radius:999px;background:rgba(3,9,7,.82);color:#9aacA4;padding:5px 8px;font:800 8px/1.1 ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:.025em}.s16-mini-guide{margin-top:9px;padding:9px 10px;border:1px solid var(--line);border-radius:11px;background:rgba(255,255,255,.015);font-size:8px;color:var(--muted);line-height:1.4}.s16-mini-guide b{color:var(--text)}
@media(max-width:520px){.s16-focus{grid-template-columns:1fr 1fr}.s16-focus div:last-child{grid-column:1/-1}.s16-today h2{font-size:20px}.s16-build{font-size:7px;max-width:58vw;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}}
`;document.head.appendChild(style);
const originalRunDay=S.runDay;
const userGame=()=>S.userGame?.();
const opponent=()=>{const g=userGame();if(!g)return null;const us=S.state.coach.team,code=g.away===us?g.home:g.away;return S.state.league[code]||null};
const injured=()=>S.state.league[S.state.coach.team]?.roster?.filter(p=>p.status==='IR'||p.health<75).length||0;
const tired=()=>S.state.league[S.state.coach.team]?.roster?.filter(p=>p.status==='ACT'&&p.fatigue>=55).length||0;
const expected=()=>{try{return R?.expectedWins?.(S.state.coach.team)?.toFixed?.(1)||null}catch(e){return null}};
const roleFocus=(role,day)=>{const hc=[['Review the team','Film, medical and staff follow-up'],['Set the plan','Opponent, personnel and staff alignment'],['Install the base','Early-down execution and communication'],['Win third down','Protection, pressure and situational work'],['Finish the plan','Red zone, two-minute and corrections'],['Lock game roles','Walkthrough and final alerts'],['Coach the game','Situational management and adjustments']];const oc=[['Grade the offense','QB, protection and usage review'],['Attack the defense','Fronts, coverages and matchup plan'],['Install the offense','Runs, dropbacks and early downs'],['Solve pressure','Third down and protection answers'],['Finish scoring plan','Red zone and two-minute'],['Lock the call sheet','Openers, roles and QB reminders'],['Call the offense','Possession-by-possession adjustments']];const dc=[['Grade the defense','Explosives, tackling and communication'],['Study the offense','QB, protection and formation tendencies'],['Install the defense','Fronts, fits and base coverages'],['Build pressure plan','Third down, rush and checks'],['Finish situational plan','Red zone and two-minute defense'],['Lock calls and alerts','Substitutions, motions and checks'],['Call the defense','Possession-by-possession adjustments']];return(role==='OC'?oc:role==='DC'?dc:hc)[day]};
const issueText=()=>{const i=injured(),f=tired();if(i>=3)return `${i} players need injury attention`;if(f>=3)return `${f} active players are carrying notable fatigue`;const logs=S.state.logs||[];const last=logs.find(x=>x.type==='meeting'||x.type==='club'||x.type==='injury');return last?last.title:'No major staff issue today'};
const todayHtml=()=>{const s=S.state.season,role=S.state.coach.role,day=s.day,opp=opponent(),focus=roleFocus(role,day),g=userGame(),isBye=!g&&s.phase==='REGULAR';const primary=day===6?(S.state.liveGame?'Return to Game Day':S.state.completedWeek===s.week?'Advance Week':'Enter Game Day'):`Complete ${S.DAYS[day]}`;const oppLabel=isBye?'Bye week':opp?`${opp.code} · ${Math.round((R?.getTeamStrength?.(opp.code)?.overall)||opp.power||0)} OVR`:'League week';return `<section class="s16-today"><div class="s16-top"><div><div class="eyebrow">TODAY · ${esc(role)}</div><h2>${esc(focus[0])}</h2><p>${esc(focus[1])}</p></div><div class="s16-daybadge">${esc(S.DAYS[day].toUpperCase())}</div></div><div class="s16-focus"><div><b>${esc(oppLabel)}</b><span>${isBye?'Recovery, self-scout and development.':'Opponent context'}</span></div><div><b>${injured()} injured · ${tired()} tired</b><span>Availability snapshot</span></div><div><b>${esc(issueText())}</b><span>What needs attention</span></div></div><button class="s16-primary" data-s16="primary">${esc(primary)}</button><div class="s16-secondaryrow"><button class="s16-secondary" data-s16="team">Open Team</button><button class="s16-secondary" data-s16="details">${S.state.ui.s16Expanded?'Hide Detail':'More Detail'}</button></div><div class="s16-mini-guide"><b>You do not need to change everything every day.</b> Handle the main task, react when something matters, and use Team/Game Plan only when you actually want deeper control.</div></section>`};
const eliminatedHtml=()=>{const P=S.state.postseason||{},round=P.roundName||'NFL Playoffs';return `<section class="s16-today s16-offseason-watch"><div class="s16-top"><div><div class="eyebrow">YOUR SEASON IS COMPLETE</div><h2>Evaluate. Scout. Watch the league.</h2><p>You missed the playoffs, so your team is no longer practicing for games. The staff is shifting to player evaluations, roster planning and offseason preparation while the NFL postseason continues.</p></div><div class="s16-daybadge">${esc(round.toUpperCase())}</div></div><div class="s16-focus"><div><b>${esc(S.record(S.state.league[S.state.coach.team]))}</b><span>Final regular-season record</span></div><div><b>${expected()||'—'} expected wins</b><span>Context for ownership</span></div><div><b>${Math.round(S.state.coach.jobSecurity||50)} job security</b><span>Career pressure</span></div></div><button class="s16-primary" data-s16="playoff-round">Simulate ${esc(round)}</button><div class="s16-secondaryrow"><button class="s16-secondary" data-s16="team">Review Player Files</button><button class="s16-secondary" data-s16="career">View Career</button></div><div class="s16-note">No fake playoff practices. Your team remains inactive while the league bracket advances.</div></section>`};
const patchGameLog=()=>{const role=S.state.coach.role;for(const x of (S.state.logs||[]).slice(0,30)){if(x.title==='Game day started'&&String(x.text||'').includes('You control the offense between possessions'))x.text=role==='OC'?'You control the offense between possessions. Your preparation and adjustments feed each drive.':role==='DC'?'You control the defense between possessions. Your pressure, coverage and personnel choices feed each drive.':'You manage the game between possessions with situational, staff and team-wide adjustments.'}}
const cleanWeek=()=>{if(S.state.ui.tab!=='week'||S.state.season.phase==='OFFSEASON')return;const main=document.querySelector('main.app')||document.getElementById('app');if(!main)return;document.querySelectorAll('.s16-today').forEach(x=>x.remove());const eliminated=S.state.season.phase==='POSTSEASON'&&S.state.postseason?.userResult==='Missed playoffs';const hero=main.querySelector('.hero');hero?.insertAdjacentHTML('afterend',eliminated?eliminatedHtml():todayHtml());const sections=[...main.querySelectorAll('section')];for(const sec of sections){if(sec.classList.contains('s16-today'))continue;const h=sec.querySelector('.section-head h2')?.textContent?.trim();if(h==='Week plan'||h==='Football operations log'||sec.querySelector('[data-action="advance-day"]'))sec.classList.toggle('s16-hidden',!S.state.ui.s16Expanded);if(eliminated&&(h==='Week plan'||sec.querySelector('[data-action="advance-day"]')||sec.classList.contains('matchup')))sec.classList.add('s16-hidden')}
};
const buildStamp=()=>{document.querySelectorAll('.s15-build-stamp,.s16-build').forEach(x=>x.remove());const e=document.createElement('div');e.className='s16-build';e.textContent=`${S.BUILD.label} · v${S.BUILD.version}`;document.body.appendChild(e)};
const oldRender=S.render;S.render=()=>{oldRender();if(typeof document==='undefined')return;patchGameLog();cleanWeek();buildStamp()};
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-s16]');if(!b)return;e.preventDefault();e.stopPropagation();const a=b.dataset.s16;if(a==='details'){S.state.ui.s16Expanded=!S.state.ui.s16Expanded;S.save();S.render();return}if(a==='team'){S.state.ui.tab='team';S.save();S.render();return}if(a==='career'){S.state.ui.tab='career';S.save();S.render();return}if(a==='primary'){const s=S.state.season;if(s.day===6){if(S.state.liveGame||S.state.completedWeek!==s.week){S.state.ui.tab='game';S.save();S.render()}else originalRunDay()}else originalRunDay();return}if(a==='playoff-round'){const wk=S.state.season.week;if(S.state.completedWeek===wk){originalRunDay();return}S.state.season.day=6;originalRunDay();if(!S.state.liveGame&&S.state.completedWeek===wk)originalRunDay();return}},true);
S.runDay=(...args)=>{const eliminated=S.state.season.phase==='POSTSEASON'&&S.state.postseason?.userResult==='Missed playoffs';if(eliminated&&S.state.season.day<6)S.state.season.day=6;return originalRunDay(...args)};
const oldAudit=S.realismAudit;S.realismAudit=()=>{const a=oldAudit();return{...a,version:'11.13-simple-coach-flow',checks:{...a.checks,simpleTodayFlow:true,detailsProgressiveDisclosure:true,eliminatedPostseasonFlow:true,roleSpecificGameLanguage:true,buildTimestamp:true}}};
S.render();
})();