(()=>{
const S=window.SUNDAY,R=S?.R;if(!S||!R||S._realism10)return;S._realism10=true;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const pick=(key,a)=>a[Math.floor(R.hashRoll(key)*a.length)%a.length];
const teamName=code=>{const t=S.state.league[code];return t?`${t.city} ${t.nick}`:code};
const mediaState=()=>{S.state.pressMemory=S.state.pressMemory||{questions:[],topics:[],conferences:[]};return S.state.pressMemory};
const recentGames=(team,n=6)=>{const out=[];for(let w=1;w<=18;w++)for(const g of S.state.schedule.weeks[w]||[])if(g.played&&g.score&&(g.away===team||g.home===team)){const opp=g.away===team?g.home:g.away,pf=g.score[team],pa=g.score[opp];out.push({week:w,opp,pf,pa,won:pf>pa,tied:pf===pa,margin:pf-pa})}return out.sort((a,b)=>b.week-a.week).slice(0,n)};
const streakOf=games=>{if(!games.length)return{type:'none',n:0};const first=games[0],type=first.tied?'tie':first.won?'win':'loss';let n=0;for(const g of games){const t=g.tied?'tie':g.won?'win':'loss';if(t!==type)break;n++}return{type,n}};
const priorMeeting=(team,opp,week)=>{const a=[];for(let w=1;w<week;w++)for(const g of S.state.schedule.weeks[w]||[])if(g.played&&g.score&&((g.away===team&&g.home===opp)||(g.home===team&&g.away===opp)))a.push({week:w,pf:g.score[team],pa:g.score[opp]});return a.at(-1)||null};
const recentPress=()=>{const m=mediaState();return new Set(m.questions.slice(0,18).map(x=>x.text))};
const add=(bank,topic,q,choices,priority=50,meta={})=>{if(!q)return;bank.push({topic,q,choices,priority,playerId:meta.playerId,meta})};
const choices={
 result:[['Own exactly what happened','accountable'],['Credit the players and keep perspective','protect'],['Explain the football adjustment','tactical']],
 player:[['Protect the player publicly','protect'],['Set a clear performance standard','demanding'],['Share responsibility across player and staff','balanced']],
 tactical:[['Explain the adjustment without giving away the plan','tactical'],['Put execution first','demanding'],['Own the coaching part','accountable']],
 history:[['Acknowledge the history but keep this team in the present','balanced'],['Say the lesson changed how you coach','accountable'],['Reject the comparison and focus on this locker room','protect']],
 pressure:[['Accept the pressure as part of the job','accountable'],['Point to the program trajectory','balanced'],['Keep the focus on players and the next week','protect']],
 relationship:[['Stand by what I said','accountable'],['Clarify the context','balanced'],['Protect the player and move forward','protect']]
};
S.buildPress=G=>{const st=S.state,us=st.coach.team,opp=G.away===us?G.home:G.away,t=st.league[us],oppT=st.league[opp],rec=S.record(t),stats=Object.values(G.stats).filter(x=>x.team===us),q=stats.find(x=>x.pos==='QB'),skill=stats.filter(x=>['WR','TE','RB'].includes(x.pos)).sort((a,b)=>(b.recYds+b.rushYds)-(a.recYds+a.rushYds))[0],drop=stats.filter(x=>['WR','TE'].includes(x.pos)).sort((a,b)=>b.drops-a.drops)[0],olPress=stats.filter(x=>['OT','OG','C','OL'].includes(x.pos)).reduce((n,x)=>n+x.pressuresAllowed,0),def=stats.filter(x=>['DL','LB','DB'].includes(x.pos)),defSacks=def.reduce((n,x)=>n+x.defSacks,0),takeaways=def.reduce((n,x)=>n+x.defInt,0),margin=G.score[us]-G.score[opp],won=margin>0,close=Math.abs(margin)<=7,blow=Math.abs(margin)>=17,games=recentGames(us,8),streak=streakOf(games),week=st.season.week,bank=[],key=G.id;
const resultVariants=won?(blow?[`You beat ${teamName(opp)} by ${margin} and moved to ${rec}. What convinced you this was more than one good Sunday?`,`That was a ${margin}-point win over ${teamName(opp)}. Where did the game actually turn?`,`At ${rec}, you just handled ${teamName(opp)} ${G.score[us]}-${G.score[opp]}. What part of that performance is sustainable?`]:close?[`You survived ${teamName(opp)} ${G.score[us]}-${G.score[opp]}. What did your team do late that it could not afford to get wrong?`,`A one-score win puts you at ${rec}. Was that composure, execution, or simply making one more play than ${teamName(opp)}?`,`You got out of this one by ${margin}. What will the film say was better than the final margin suggests?`]:[`You are ${rec} after beating ${teamName(opp)} ${G.score[us]}-${G.score[opp]}. What mattered most beyond the scoreboard?`,`What did this win over ${teamName(opp)} reveal about your team that you did not know a week ago?`,`You moved to ${rec}. Which part of today's win best reflects what you want this team to become?`]):(blow?[`${teamName(opp)} beat you by ${Math.abs(margin)}. What failed first: preparation, adjustment, or execution?`,`At ${rec}, this was a decisive loss. What responsibility belongs specifically to the coaching staff?`,`The score got away from you against ${teamName(opp)}. What on that tape worries you beyond one bad game?`]:close?[`You lost to ${teamName(opp)} by ${Math.abs(margin)}. Which late-game detail do you expect to revisit first?`,`A one-score loss leaves you ${rec}. Was there a decision you would handle differently?`,`This came down to a few possessions. What separated ${teamName(opp)} from you today?`]:[`You are ${rec} after losing ${G.score[us]}-${G.score[opp]}. What is the most important correction before next week?`,`What did ${teamName(opp)} expose today that your staff has to solve?`,`How do you separate a bad result from a warning sign after this loss to ${teamName(opp)}?`]);
add(bank,'result',pick(key+'result',resultVariants),choices.result,100,{opp,margin});
if(q&&(q.int>=2||q.sacks>=4||q.passTD>=3)){
 const bad=q.int>=2||q.sacks>=4;const qq=bad?pick(key+'qb',[`${q.name} had ${q.int} interceptions and took ${q.sacks} sacks. How do you divide responsibility between him, protection and the plan?`,`With ${q.name} under that much stress today, what do you need to change before asking him to play better?`,`${q.name}'s line was ${q.passTD} TD, ${q.int} INT with ${q.sacks} sacks taken. What did you see that the box score does not explain?`]):pick(key+'qbhot',[`${q.name} threw ${q.passTD} touchdowns. How much of that was his growth versus what the staff created for him?`,`What did ${q.name} handle today that shows he is seeing the offense differently?`,`${q.name} produced one of his better scoring days. What part of his process impressed you most?`]);
 add(bank,'quarterback',qq,choices.player,84,{playerId:q.playerId});
}
if(olPress>=5)add(bank,'protection',pick(key+'ol',[`Your offensive line allowed ${olPress} charted pressures. Does the fix start with personnel, technique or protection design?`,`There were ${olPress} pressures on your quarterback. How much of that belongs on your call sheet?`,`Protection broke down ${olPress} times by your charting. Are roles on the offensive line now under review?`]),choices.tactical,80);
if(skill){const p=S.findPlayer(skill.playerId),usage=skill.rushAtt+skill.targets;if(usage>=12||skill.recYds+skill.rushYds>=90)add(bank,'featured-player',pick(key+'skill',[`${skill.name} accounted for ${skill.recYds+skill.rushYds} scrimmage yards. Was that matchup-specific or is his role changing?`,`${skill.name} got ${usage} opportunities today. Did he earn more of the offense going forward?`,`How much of today's plan was built around creating touches for ${skill.name}, and how much emerged during the game?`]),choices.player,72,{playerId:p?.id||skill.playerId});}
if(drop?.drops>=2)add(bank,'drops',pick(key+'drops',[`${drop.name} had ${drop.drops} drops. How do you correct that without changing the player's confidence?`,`You kept managing ${drop.name}'s role after ${drop.drops} drops. What message are you sending him this week?`,`${drop.name}'s ${drop.drops} drops were visible mistakes. What will matter more to you: his response in practice or his prior body of work?`]),choices.player,76,{playerId:drop.playerId});
if(defSacks>=4||takeaways>=2)add(bank,'defense',pick(key+'def',[`Your defense finished with ${defSacks} sacks and ${takeaways} interceptions. Was that the plan winning or players taking over the game?`,`The defense generated ${defSacks+takeaways} splash plays. Which part of that can you reliably carry into next week?`,`How much credit goes to the defensive staff for creating ${defSacks} sacks and ${takeaways} picks today?`]),choices.tactical,70);
if(streak.n>=3)add(bank,'season-streak',pick(key+'streak',[`This is now ${streak.n} straight ${streak.type==='win'?'wins':'losses'}. At what point does a streak become evidence of what a team really is?`,`You have ${streak.n} consecutive ${streak.type==='win'?'wins':'losses'}. What has changed during that stretch?`,`After ${streak.n} straight ${streak.type==='win'?'wins':'losses'}, are you seeing a trend or still treating every week independently?`]),choices.result,74,{streak});
const expected=R.expectedWins?.(),gamesPlayed=t.teamStats.games||1,pace=(t.teamStats.w/gamesPlayed)*17;if(Number.isFinite(expected)&&gamesPlayed>=6&&Math.abs(pace-expected)>=2.2){const ahead=pace>expected;add(bank,'expectations',pick(key+'exp',[`Your current pace is roughly ${pace.toFixed(1)} wins against a preseason-quality expectation around ${expected.toFixed(1)}. ${ahead?'Why is this team ahead of the roster projection?':'Why has the roster not translated into the expected results?'}`,`${gamesPlayed} games in, the results are ${ahead?'running ahead of':'behind'} the roster-based expectation. What is the biggest reason?`,`${ahead?'You are outperforming':'You are underperforming'} the talent expectation so far. How much of that belongs to coaching?`]),choices.pressure,72,{expected,pace:+pace.toFixed(1)});}
const prior=priorMeeting(us,opp,week);if(prior)add(bank,'opponent-history',pick(key+'rematch',[`You saw ${teamName(opp)} earlier this season in a ${prior.pf}-${prior.pa} game. What was materially different this time?`,`This was your second look at ${teamName(opp)} this year. Which adjustment from the first meeting mattered most?`,`How much did the first ${teamName(opp)} game shape today's plan, and where did you deliberately change course?`]),choices.history,67,{prior});
const review=st.ownershipReviews?.[0];if(review&&['Hot Seat','Critical'].includes(review.status))add(bank,'job-security',pick(key+'job',[`Your most recent ownership evaluation put you on the ${review.status.toLowerCase()}. Do you coach differently when every result is being judged?`,`Ownership has publicly meaningful pressure on this program. How do you keep that from reaching the locker room?`,`Your job-security profile is under pressure. What should ownership evaluate that the record alone cannot show?`]),choices.pressure,68,{review:review.score});
const seasons=st.history?.seasons||[],lastSeason=seasons.find(x=>x.year<st.season.year);if(lastSeason&&week>=5&&R.hashRoll(key+'history-season')<.34){const same=lastSeason.team===us;add(bank,'career-history',pick(key+'hist',[same?`Last season ended ${lastSeason.record}${lastSeason.postseason?` with ${lastSeason.postseason}`:''}. What from that year is still shaping this team?`:`Your last full season with ${lastSeason.team} ended ${lastSeason.record}. What did that experience change about how you are coaching ${us}?`,same?`There were lessons from last year's ${lastSeason.record} finish. Which one is showing up most in this season?`:`You have coached in a different building and role before. What part of that history is most useful to you now?`,same?`How much of this season is a continuation of last year, and how much is a different team entirely?`:`When you compare this locker room to your previous stop in ${lastSeason.team}, what has required the biggest adjustment from you?`]),choices.history,52,{lastSeason});}
const firing=st.history?.firings?.[0];if(firing&&firing.team!==us&&R.hashRoll(key+'firing')<.22)add(bank,'firing-history',pick(key+'fire',[`You were dismissed by ${firing.team} earlier in your career. Does a game like this change how you think about that chapter?`,`How much did being fired by ${firing.team} alter the standards you set in your next job?`,`You have already lived through a firing in this league. Does that make current pressure easier to manage or harder to ignore?`]),choices.history,48,{firing});
const oldTeam=R.ensureCoachProfile?.().roleHistory?.find(x=>x.team===opp&&x.team!==us);if(oldTeam)add(bank,'former-team',pick(key+'oldteam',[`You are facing ${teamName(opp)}, one of your former organizations. Was there anything emotionally different about this week?`,`How much of your history with ${opp} actually helped today, and how much is too old to matter?`,`You know this organization from the inside. Did that history affect how you prepared for ${teamName(opp)}?`]),choices.history,86,{oldTeam});
const prevQa=(st.media||[]).flatMap(x=>x.qa||[]).find(x=>x&&x.tone);if(prevQa&&R.hashRoll(key+'quote')<.3){const answer=String(prevQa.answer||'').slice(0,90);add(bank,'prior-quote',pick(key+'quotev',[`Earlier you said, "${answer}". Does today's game reinforce that or change your view?`,`You have been consistent publicly about this team. After today, is there anything from your recent comments you would revise?`,`A recent answer from you was, "${answer}". What has happened since then that gives that statement more context?`]),choices.relationship,58,{priorAnswer:answer});}
const used=recentPress(),seenTopics=new Set(),selected=[];const eligible=bank.filter(x=>!used.has(x.q)).sort((a,b)=>b.priority-a.priority||R.hashRoll(key+a.topic)-R.hashRoll(key+b.topic));const result=eligible.find(x=>x.topic==='result')||bank.find(x=>x.topic==='result');if(result){selected.push(result);seenTopics.add(result.topic)}for(const x of eligible){if(selected.length>=3)break;if(seenTopics.has(x.topic)||x===result)continue;selected.push(x);seenTopics.add(x.topic)}if(selected.length<3)for(const x of bank){if(selected.length>=3)break;if(!selected.some(y=>y.q===x.q)){selected.push(x);seenTopics.add(x.topic)}}const m=mediaState();for(const x of selected){m.questions.unshift({season:st.season.year,week,text:x.q,topic:x.topic});m.topics.unshift({season:st.season.year,week,topic:x.topic})}m.questions=m.questions.slice(0,80);m.topics=m.topics.slice(0,100);S.state.pressConference={gameId:G.id,index:0,answers:[],questions:selected.map(x=>({q:x.q,choices:x.choices,playerId:x.playerId,topic:x.topic,meta:x.meta})),complete:false,context:{season:st.season.year,week,team:us,opponent:opp,record:rec,margin}}};
const oldAnswer=S.answerPress;S.answerPress=i=>{const pc=S.state.pressConference,q=pc&&!pc.complete?pc.questions[pc.index]:null,out=oldAnswer(i);if(pc?.complete){const media=(S.state.media||[])[0];if(media){media.qa=pc.answers.map((a,j)=>({...a,topic:pc.questions[j]?.topic,meta:pc.questions[j]?.meta}));media.context=pc.context;media.text=media.qa.map(x=>`${x.question} — ${x.answer}`).join(' · ')}const m=mediaState();m.conferences.unshift({season:S.state.season.year,week:S.state.season.week,gameId:pc.gameId,topics:pc.questions.map(x=>x.topic),qa:pc.answers.map((a,j)=>({...a,topic:pc.questions[j]?.topic}))});m.conferences=m.conferences.slice(0,40)}S.save?.();return out};
const oldAudit=S.realismAudit;S.realismAudit=()=>{const a=oldAudit(),m=mediaState();return{...a,version:'11.7-media-memory',press:{storedQuestions:m.questions.length,conferences:m.conferences.length},checks:{...a.checks,contextualPress:true,reporterMemory:true,careerHistoryQuestions:true,noRecentExactRepeats:true}}};if(window.SUNDAY_QA){window.SUNDAY_QA.realismAudit=S.realismAudit;window.SUNDAY_QA.buildPress=S.buildPress}
S.render();
})();