(()=>{
const S=window.SUNDAY,R=S?.R;if(!S||!R||S._realism6)return;S._realism6=true;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const avg=a=>a.length?a.reduce((n,x)=>n+x,0)/a.length:0;
R.captureSeasonBaseline=()=>{const t=R.team();S.state.coachEvaluation=S.state.coachEvaluation||{};const key=`${S.state.season.year}-${t.code}`;if(!S.state.coachEvaluation.baselines)S.state.coachEvaluation.baselines={};if(!S.state.coachEvaluation.baselines[key])S.state.coachEvaluation.baselines[key]={players:Object.fromEntries(t.roster.filter(p=>p.status==='ACT').map(p=>[p.id,p.overall])),teamPower:t.power,stamp:Date.now()};};
R.regularUserGames=()=>{const us=S.state.coach.team,out=[];for(let w=1;w<=18;w++)for(const g of S.state.schedule.weeks[w]||[])if(g.played&&g.score&&(g.away===us||g.home===us)){const opp=g.away===us?g.home:g.away,won=g.score[us]>g.score[opp],tied=g.score[us]===g.score[opp];out.push({week:w,won,tied,pf:g.score[us],pa:g.score[opp]})}return out.sort((a,b)=>a.week-b.week)};
R.expectedWins=()=>{const t=R.team(),top=t.roster.filter(p=>p.status==='ACT').sort((a,b)=>b.overall-a.overall).slice(0,25),quality=avg(top.map(p=>p.overall))||76;return clamp(6.3+((t.power||76)-76)*.22+(quality-77)*.15,4.5,12)};
R.developmentScore=()=>{const t=R.team(),key=`${S.state.season.year}-${t.code}`,base=S.state.coachEvaluation?.baselines?.[key]?.players||{},deltas=[];for(const p of t.roster){if(Number.isFinite(base[p.id]))deltas.push(p.overall-base[p.id])}const delta=deltas.length?avg(deltas):0,rookies=t.roster.filter(p=>p.contract?.rookie&&p.status==='ACT'),rookieProgress=rookies.length?avg(rookies.map(p=>p.overall-(base[p.id]??p.overall))):0;return{delta,score:clamp(7.5+delta*3.4+rookieProgress*1.2,0,15)}};
R.evaluateOwnership=()=>{const st=S.state,t=R.team(),games=R.regularUserGames(),wins=t.teamStats.w,ties=t.teamStats.t||0,expected=R.expectedWins(),priorReviews=(st.ownershipReviews||[]).filter(x=>x.team===t.code),prior=priorReviews[0]||null,prevWins=prior?.wins??null,trajectory=prevWins===null?7.5:wins-prevWins>=3?15:wins-prevWins===2?13:wins-prevWins===1?11:wins-prevWins===0?8:wins-prevWins===-1?6:wins-prevWins===-2?4:1;
const active=t.roster.filter(p=>p.status==='ACT'),trust=avg(active.map(p=>p.trust||50)),confidence=avg(active.map(p=>p.confidence||50)),cultureIndex=avg([st.morale.overall||50,st.morale.coachTrust||50,st.morale.cohesion||50,trust,confidence]),culture=clamp((cultureIndex-30)/2,0,20),dev=R.developmentScore(),first=games.slice(0,6),last=games.slice(-6),firstWins=first.reduce((n,g)=>n+(g.won?1:g.tied?.5:0),0),lateWins=last.reduce((n,g)=>n+(g.won?1:g.tied?.5:0),0),late=clamp(5+(lateWins-3)*1.25+(lateWins-firstWins)*.35,0,10),pdg=(t.teamStats.games?((t.teamStats.points||0)-(t.teamStats.pa||0))/t.teamStats.games:0),execution=clamp(5+pdg*.35,0,10),alignmentIndex=avg([st.coach.reputation||50,st.morale.coachTrust||50]),alignment=clamp((alignmentIndex-30)/8,0,5),performance=clamp(12.5+(wins+ties*.5-expected)*2.5,0,25),post=st.postseason?.userResult||'Missed playoffs',playoffBonus=post==='Won Super Bowl'?18:post==='Lost Super Bowl'?13:post.includes('conference')?10:post.includes('divisional')?7:post.includes('wild card')?5:post==='Qualified'?4:0,score=clamp(performance+trajectory+culture+dev.score+late+execution+alignment+playoffBonus,0,100),tenure=priorReviews.length+1,priorDanger=prior&&['Hot Seat','Critical'].includes(prior.status),threeBad=[...priorReviews.slice(0,2).map(x=>x.wins),wins].length>=3&&[...priorReviews.slice(0,2).map(x=>x.wins),wins].every(x=>x<=7),organizationalBreak=cultureIndex<38&&alignmentIndex<42&&lateWins<=2,catastrophic=wins<=3&&score<48,missedBadly=wins<expected-4.25,playoff=post!=='Missed playoffs'&&post!=='Season complete';let fired=false;
if(!playoff){if(score<27)fired=true;else if(tenure===1&&wins<=2&&cultureIndex<38&&score<34)fired=true;else if(tenure>=2&&catastrophic)fired=true;else if(tenure>=2&&priorDanger&&score<47&&wins<=7)fired=true;else if(tenure>=3&&threeBad&&score<54)fired=true;else if(organizationalBreak&&missedBadly)fired=true}else if(cultureIndex<28&&alignmentIndex<30&&score<25)fired=true;
const status=fired?'Fired':score>=75?'Secure':score>=60?'Stable':score>=50?'Watch':score>=38?'Hot Seat':'Critical';
return{season:st.season.year,team:t.code,wins,losses:t.teamStats.l,ties,expected:+expected.toFixed(1),score:+score.toFixed(1),status,fired,postseason:post,performance:+performance.toFixed(1),trajectory:+trajectory.toFixed(1),culture:+culture.toFixed(1),cultureIndex:+cultureIndex.toFixed(1),development:+dev.score.toFixed(1),developmentDelta:+dev.delta.toFixed(2),late:+late.toFixed(1),lateWins,execution:+execution.toFixed(1),pointDiffPerGame:+pdg.toFixed(1),alignment:+alignment.toFixed(1),alignmentIndex:+alignmentIndex.toFixed(1),tenure};};
R.buildJobMarket=review=>{const old=review.team,candidates=Object.values(S.state.league).filter(t=>t.code!==old).sort((a,b)=>a.teamStats.w-b.teamStats.w||a.power-b.power).slice(0,5),count=S.state.coach.reputation>=65?3:S.state.coach.reputation>=50?2:1,choices=candidates.slice(0,count).map(t=>({label:`Interview for ${t.code} head coach job`,act:'jobInterview',team:t.code}));choices.push({label:'Sit out this hiring cycle',act:'jobSit'});S.state.decisions=[{type:'jobMarket',title:'Head-coach hiring cycle',body:`${old} moved on after the ${review.season} season. Your reputation is ${Math.round(S.state.coach.reputation)}. Other clubs will judge the full record: results, development, culture and trajectory.`,choices}]};
R.fireCoach=review=>{const st=S.state;st.coach.employed=false;st.coach.jobSecurity=0;st.careerStatus='FIRED';st.history.firings=st.history.firings||[];st.history.firings.unshift({season:review.season,team:review.team,score:review.score,reason:`Ownership review: ${review.status}`});S.addLog?.('career','Head coach dismissed',`${review.team} ownership dismissed the head coach after a ${review.wins}-${review.losses} season. Ownership score: ${review.score}. Culture ${review.cultureIndex}, development ${review.developmentDelta>=0?'+':''}${review.developmentDelta}, late-season wins ${review.lateWins}/6.`);R.buildJobMarket(review)};
R.applyOwnershipReview=()=>{S.state.ownershipReviews=S.state.ownershipReviews||[];const r=R.evaluateOwnership();S.state.ownershipReviews.unshift(r);S.state.coach.jobSecurity=r.fired?0:clamp(Math.round(r.score),18,95);S.addLog?.('career','Ownership evaluation',`Score ${r.score}/100 - ${r.status}. Results ${r.wins}-${r.losses} vs ${r.expected} expected wins; culture ${r.cultureIndex}; development ${r.developmentDelta>=0?'+':''}${r.developmentDelta}; late stretch ${r.lateWins}/6 wins.`);if(r.fired)R.fireCoach(r);else{const d=S.state.decisions.find(x=>x.type==='career');if(d)d.body+=` Ownership review: ${r.status} (${r.score}/100). Results are only part of it - culture, development, trajectory and late-season direction were graded too.`}S.save?.();return r};
const priorEnd=S.endSeason;S.endSeason=()=>{const out=priorEnd();R.applyOwnershipReview();S.render?.();return out};
const priorResolve=S.resolveDecision;S.resolveDecision=i=>{const d=S.state.decisions[0],c=d?.choices?.[i];if(d?.type==='jobMarket'&&c){S.state.decisions.shift();if(c.act==='jobSit'){S.state.careerStatus='UNEMPLOYED';S.addLog?.('career','Hiring cycle passed','No head-coaching job accepted this cycle.');S.save();S.render();return}const chance=clamp(.38+(S.state.coach.reputation-45)/110+(S.state.ownershipReviews?.[0]?.score||45)/300,.28,.82),roll=R.hashRoll(`${S.state.season.year}|${c.team}|interview|${S.state.coach.name}`);if(roll<=chance){const old=S.state.coach.team;S.state.coach.team=c.team;S.state.coach.employed=true;S.state.careerStatus='EMPLOYED';S.state.coach.jobSecurity=55;S.state.coach.reputation=clamp(S.state.coach.reputation-1,25,95);S.state.frontOffice={owner:`${c.team} ownership`,gm:`${c.team} general manager`};S.state.staff={hc:{name:S.state.coach.name,title:'Head Coach',quality:82},oc:{name:'Offensive Coordinator',title:'Offensive Coordinator',quality:80},dc:{name:'Defensive Coordinator',title:'Defensive Coordinator',quality:80},st:{name:'Special Teams Coordinator',title:'Special Teams Coordinator',quality:80}};S.state.offseason={stage:7,moves:[`Hired as ${c.team} head coach`]};S.addLog?.('career','Hired as head coach',`${c.team} hired you after the interview process. Career continues after the ${old} dismissal.`)}else{S.addLog?.('career','Head-coach interview',`${c.team} chose another candidate.`);const remaining=d.choices.filter((x,j)=>j!==i);if(remaining.some(x=>x.act==='jobInterview'))S.state.decisions=[{...d,choices:remaining,body:`${c.team} chose another candidate. Other opportunities remain.`}];else S.state.careerStatus='UNEMPLOYED'}S.save();S.render();return}return priorResolve(i)};
const priorNew=S.newSeason;S.newSeason=()=>{const out=priorNew();R.captureSeasonBaseline();return out};
const priorRender=S.render;S.render=()=>{priorRender();if(typeof document==='undefined')return;const main=document.querySelector('main.app');if(!main||S.state.ui.tab!=='career')return;const r=S.state.ownershipReviews?.[0];if(!r)return;main.insertAdjacentHTML('afterbegin',`<section class="section realism-card"><div class="section-head"><h2>Ownership evaluation</h2><span>${r.status} · ${r.score}/100</span></div><div class="card grid3"><div class="metric"><b>${r.wins}-${r.losses}</b><span>record</span></div><div class="metric"><b>${r.expected}</b><span>expected wins</span></div><div class="metric"><b>${r.lateWins}/6</b><span>late-season wins</span></div><div class="metric"><b>${r.cultureIndex}</b><span>culture</span></div><div class="metric"><b>${r.developmentDelta>=0?'+':''}${r.developmentDelta}</b><span>player development</span></div><div class="metric"><b>${r.pointDiffPerGame>0?'+':''}${r.pointDiffPerGame}</b><span>point diff / game</span></div></div><div class="notice">Ownership grades the whole program: performance vs roster expectations, trajectory, culture, player development, late-season direction, execution and organizational trust.</div></section>`)};
R.captureSeasonBaseline();
const priorAudit=S.realismAudit;S.realismAudit=()=>{const a=priorAudit(),r=S.state.ownershipReviews?.[0];return{...a,version:'11.4-career',ownershipReview:r||null,checks:{...a.checks,firingSystem:true,ownershipModel:!!R.evaluateOwnership}}};if(window.SUNDAY_QA){window.SUNDAY_QA.realismAudit=S.realismAudit;window.SUNDAY_QA.evaluateOwnership=R.evaluateOwnership}
S.render();
})();
