(()=>{
const S=window.SUNDAY,R=S?.R;if(!S||!R||S._realism3)return;S._realism3=true;
R.ensureRules=()=>{R.ensure();const p=S.state.practiceRules;p.earlyUsed=Number.isFinite(p.earlyUsed)?p.earlyUsed:0;p.lateUsed=Number.isFinite(p.lateUsed)?p.lateUsed:0;p.postWeeks=p.postWeeks||[];p.firstElevenLimit=11;p.finalSixLimit=3};
R.ensureRules();
R.prepareGameDay=()=>{const st=S.state,t=R.team();R.restoreGameDay();let a=t.roster.filter(p=>p.status==='ACT');const score=p=>(['Featured','Starter'].includes(p.role)?100:0)+(p.pos==='QB'?25:0)+p.overall+(p.trust||50)/20,ols=a.filter(p=>['OT','OG','C','OL'].includes(p.pos)).sort((x,y)=>score(y)-score(x)),max=ols.length>=8?48:47,target=Math.min(max,a.length);if(a.length<=target){st.gameDay={prepared:true,inactives:[],limit:max};return}const must=new Set(ols.slice(0,Math.min(8,ols.length)).map(p=>p.id));for(const p of a.filter(p=>['Featured','Starter'].includes(p.role)))must.add(p.id);const cut=a.filter(p=>!must.has(p.id)).sort((x,y)=>score(x)-score(y)).slice(0,a.length-target);for(const p of cut)p.status='INACTIVE';st.gameDay={prepared:true,inactives:cut.map(p=>p.id),limit:max};S.addLog?.('roster','Game-day inactive list',`${cut.length} players inactive; ${target} dressed. ${ols.length>=8?'Eight offensive linemen dressed, allowing 48 actives.':'Fewer than eight healthy offensive linemen available, so the gameday limit is 47.'}`,cut.map(p=>p.id))};
S.prepareGameDay=R.prepareGameDay;
const priorRun=S.runDay;S.runDay=()=>{R.ensureRules();const s=S.state.season,p=S.state.practiceRules,day=s.day,week=s.week,phase=s.phase,bye=phase==='REGULAR'&&!S.userGame?.();if(bye&&day>=3&&day<=5){S.addLog?.('recovery','Bye-week mandatory rest',`${S.DAYS[day]} is part of the four-day bye-week break. No practice or team work is scheduled.`);s.day++;S.save();S.render();return}let requestedPads=p.thisWeek==='Full pads'&&day===2,allowPads=requestedPads;if(requestedPads&&phase==='REGULAR'){if(week<=11&&p.earlyUsed>=11)allowPads=false;if(week>=12&&p.lateUsed>=3)allowPads=false}if(requestedPads&&phase==='POSTSEASON'){const key=`${s.year}-post-${week}`;if(p.postWeeks.includes(key))allowPads=false}if(requestedPads&&!allowPads){p.thisWeek='Shells';S.addLog?.('practice','Padded-practice rule enforced',phase==='POSTSEASON'?'Only one padded practice is permitted in a postseason week.':week<=11?'The club has used its first-11-weeks padded-practice allotment.':'The club has used its final-six-weeks padded-practice allotment.')}const before=p.paddedUsed||0;let savedTotal=null;if(requestedPads&&allowPads&&phase==='POSTSEASON'&&before>=14){savedTotal=before;p.paddedUsed=13}const out=priorRun();if(requestedPads&&allowPads){if(phase==='REGULAR'&&(p.paddedUsed||0)>before){if(week<=11)p.earlyUsed++;else p.lateUsed++}if(phase==='POSTSEASON'){const key=`${s.year}-post-${week}`;if(!p.postWeeks.includes(key))p.postWeeks.push(key);if(savedTotal!==null)p.paddedUsed=savedTotal}}S.save?.();return out};
const priorNew=S.newSeason;S.newSeason=()=>{const out=priorNew();R.ensureRules();S.state.practiceRules={paddedUsed:0,paddedLimit:14,thisWeek:'Shells',paddedWeeks:[],earlyUsed:0,lateUsed:0,postWeeks:[],firstElevenLimit:11,finalSixLimit:3};S.save();S.render();return out};
S.realismAudit=()=>{R.ensureRules();const t=R.team(),a=t.roster.filter(p=>p.status==='ACT'),ol=a.filter(p=>['OT','OG','C','OL'].includes(p.pos)).length,ps=t.roster.filter(p=>p.status==='PS').length,gd=S.state.gameDay,p=S.state.practiceRules;return{version:'11.1-realism',role:S.state.coach.role,staff:Object.values(S.state.staff).map(x=>x.name),activeRoster:a.length,olActive:ol,practiceSquad:ps,injuries:t.roster.filter(p=>p.injury).length,contractRecords:t.roster.filter(p=>p.contract).length,capRoom2027:R.capRoom(),tradeDeadline:S.state.coachMeetings.tradeDeadline||false,gamedayLimit:gd?.prepared?gd.limit:(ol>=8?48:47),padded:{total:p.paddedUsed,early:p.earlyUsed,late:p.lateUsed,postseasonWeeks:p.postWeeks.length},checks:{headCoach:S.state.coach.role==='HC',activeRosterLegal:a.length<=53,gameDayLegal:!gd?.prepared||a.length<=(gd.limit||48),gameDayOLRule:!gd?.prepared||(gd.limit===48?ol>=8:true),staffLoaded:!!S.state.staff.oc&&!!S.state.staff.dc,capNonNegative:R.capRoom()>=0,practiceSquadLegal:ps<=16,paddedPracticeLegal:p.paddedUsed<=14&&p.earlyUsed<=11&&p.lateUsed<=3}}};
if(window.SUNDAY_QA){window.SUNDAY_QA.realismAudit=S.realismAudit;window.SUNDAY_QA.startGame=S.startGame;window.SUNDAY_QA.nextDrive=S.nextDrive;window.SUNDAY_QA.resolveDecision=S.resolveDecision;window.SUNDAY_QA.advanceOffseason=S.advanceOffseason}
S.render();
})();
